export interface Project {
  id: string;
  title: string;
  subtitle: string;
  description: string;
  year: string;
  location: string;
  type: string;
  images: {
    main: string;
    gallery: string[];
    thumbnails: string[];
  };
  videos?: {
    main?: string;
    gallery?: string[];
  };
  text: {
    academic?: string;
    practical?: string;
    details?: string;
  };
}

export const projects: Project[] = [
  {
    id: 'animism',
    title: 'ANIMISM',
    subtitle: 'Algorithmic Architecture',
    description: 'A computational approach to architectural design using algorithmic processes.',
    year: '2023',
    location: 'Tel Aviv, Israel',
    type: 'Academic Research',
    images: {
      main: '/works/ANIMISM/Render.jpg',
      gallery: [
        '/works/ANIMISM/Algorithm.jpg',
        '/works/ANIMISM/Exploded.jpg',
        '/works/ANIMISM/Formation.jpg',
        '/works/ANIMISM/Mapping.jpg',
        '/works/ANIMISM/Protocell.jpg',
        '/works/ANIMISM/Render.jpg',
        '/works/ANIMISM/Section.jpg',
      ],
      thumbnails: [
        '/works/ANIMISM/thumb/Algorithm.jpg',
        '/works/ANIMISM/thumb/Exploded.jpg',
        '/works/ANIMISM/thumb/Formation.jpg',
        '/works/ANIMISM/thumb/Mapping.jpg',
        '/works/ANIMISM/thumb/Protocell.jpg',
        '/works/ANIMISM/thumb/Render.jpg',
        '/works/ANIMISM/thumb/Section.jpg',
      ],
    },
    videos: {
      main: '/works/ANIMISM/Video/Video.webm',
      gallery: [
        '/works/ANIMISM/Video/Video.webm',
        '/works/ANIMISM/Video/Macro.webm',
        '/works/ANIMISM/Video/Micro.webm',
      ],
    },
    text: {
      academic: 'This project explores the intersection of algorithmic design and architectural form, investigating how computational processes can generate organic, living-like structures.',
      practical: 'The design process involved developing custom algorithms in Grasshopper and Python to create self-organizing architectural systems.',
      details: 'The project resulted in a series of parametric models that demonstrate the potential for algorithmic architecture to create more responsive and adaptive built environments.',
    },
  },
  {
    id: 'wendy',
    title: 'WENDY',
    subtitle: 'Urban Intervention',
    description: 'A temporary urban intervention exploring public space and community interaction.',
    year: '2022',
    location: 'Tel Aviv, Israel',
    type: 'Urban Design',
    images: {
      main: '/works/WENDY/Video/Main Poster.jpg',
      gallery: [
        '/works/WENDY/Video/Main Poster.jpg',
        '/works/WENDY/Video/POV Poster.jpg',
        '/works/WENDY/Video/Poster.jpg',
      ],
      thumbnails: [
        '/works/WENDY/Video/Main Poster.jpg',
        '/works/WENDY/Video/POV Poster.jpg',
        '/works/WENDY/Video/Poster.jpg',
      ],
    },
    videos: {
      main: '/works/WENDY/Video/Video.webm',
      gallery: [
        '/works/WENDY/Video/Video.webm',
        '/works/WENDY/Video/POV Video.webm',
      ],
    },
    text: {
      academic: 'WENDY investigates the role of temporary structures in urban environments and their potential to create new forms of social interaction.',
      practical: 'The project involved community engagement workshops and iterative design processes to create a structure that responds to local needs.',
      details: 'The final intervention was constructed using sustainable materials and designed for easy assembly and disassembly.',
    },
  },
  {
    id: 'evo',
    title: 'EVO',
    subtitle: 'Evolutionary Housing',
    description: 'A housing complex designed to evolve and adapt over time.',
    year: '2021',
    location: 'Tel Aviv, Israel',
    type: 'Residential Architecture',
    images: {
      main: '/works/EVO/Render 01.jpg',
      gallery: [
        '/works/EVO/Apartment A.jpg',
        '/works/EVO/Apartment B.jpg',
        '/works/EVO/Apartment C.jpg',
        '/works/EVO/Area Plan.jpg',
        '/works/EVO/City Evolution.jpg',
        '/works/EVO/Generic Floor.jpg',
        '/works/EVO/Ground Floor.jpg',
        '/works/EVO/Parameters.jpg',
        '/works/EVO/Recreational Zones.jpg',
        '/works/EVO/Render 01.jpg',
        '/works/EVO/Render 02.jpg',
        '/works/EVO/Section A.jpg',
        '/works/EVO/Section B.jpg',
        '/works/EVO/Semi Orthogonal Cell Creation.jpg',
        '/works/EVO/Underground Floor.jpg',
      ],
      thumbnails: [
        '/works/EVO/thumb/Apartment A.jpg',
        '/works/EVO/thumb/Apartment B.jpg',
        '/works/EVO/thumb/Apartment C.jpg',
        '/works/EVO/thumb/Area Plan.jpg',
        '/works/EVO/thumb/City Evolution.jpg',
        '/works/EVO/thumb/Generic Floor.jpg',
        '/works/EVO/thumb/Ground Floor.jpg',
        '/works/EVO/thumb/Parameters.jpg',
        '/works/EVO/thumb/Recreational Zones.jpg',
        '/works/EVO/thumb/Render 01.jpg',
        '/works/EVO/thumb/Render 02.jpg',
        '/works/EVO/thumb/Section A.jpg',
        '/works/EVO/thumb/Section B.jpg',
        '/works/EVO/thumb/Semi Orthogonal Cell Creation.jpg',
        '/works/EVO/thumb/Underground Floor.jpg',
      ],
    },
    videos: {
      main: '/works/EVO/Video/Video.webm',
      gallery: [
        '/works/EVO/Video/Video.webm',
        '/works/EVO/Video/Cel Experiments.webm',
      ],
    },
    text: {
      academic: 'EVO explores the concept of evolutionary architecture, where buildings can adapt and change over time to meet changing needs.',
      practical: 'The design incorporates modular construction systems and flexible spatial configurations that allow for future modifications.',
      details: 'The project includes 150 residential units with shared amenities and flexible common spaces that can be reconfigured as needed.',
    },
  },
  {
    id: 'eaaa',
    title: 'EAAA',
    subtitle: 'Educational Architecture',
    description: 'A new educational complex designed for collaborative learning.',
    year: '2020',
    location: 'Tel Aviv, Israel',
    type: 'Educational Architecture',
    images: {
      main: '/works/EAAA/Render 01.jpg',
      gallery: [
        '/works/EAAA/0 Ground Floor.jpg',
        '/works/EAAA/2nd Floor.jpg',
        '/works/EAAA/3rd floor.jpg',
        '/works/EAAA/4th Floor.jpg',
        '/works/EAAA/5th Floor.jpg',
        '/works/EAAA/Exploded Diagram.jpg',
        '/works/EAAA/Program Diagram.jpg',
        '/works/EAAA/Render 01.jpg',
        '/works/EAAA/Render 02.jpg',
        '/works/EAAA/Render 03.jpg',
        '/works/EAAA/Section A.jpg',
        '/works/EAAA/Section B.jpg',
        '/works/EAAA/Site Anaylsis.jpg',
        '/works/EAAA/Urban Strategy.jpg',
      ],
      thumbnails: [
        '/works/EAAA/thumb/0 Ground Floor.jpg',
        '/works/EAAA/thumb/2nd Floor.jpg',
        '/works/EAAA/thumb/3rd floor.jpg',
        '/works/EAAA/thumb/4th Floor.jpg',
        '/works/EAAA/thumb/5th Floor.jpg',
        '/works/EAAA/thumb/Exploded Diagram.jpg',
        '/works/EAAA/thumb/Program Diagram.jpg',
        '/works/EAAA/thumb/Render 01.jpg',
        '/works/EAAA/thumb/Render 02.jpg',
        '/works/EAAA/thumb/Render 03.jpg',
        '/works/EAAA/thumb/Section A.jpg',
        '/works/EAAA/thumb/Section B.jpg',
        '/works/EAAA/thumb/Site Anaylsis.jpg',
        '/works/EAAA/thumb/Urban Strategy.jpg',
      ],
    },
    videos: {
      main: '/works/EAAA/video/Video.webm',
      gallery: [
        '/works/EAAA/video/Video.webm',
      ],
    },
    text: {
      academic: 'EAAA reimagines educational spaces for the 21st century, focusing on collaborative learning and interdisciplinary interaction.',
      practical: 'The design incorporates flexible learning spaces, maker labs, and digital infrastructure to support modern educational needs.',
      details: 'The complex includes classrooms, laboratories, studios, and common areas designed to encourage interaction and collaboration.',
    },
  },
  {
    id: 'mist',
    title: 'MIST',
    subtitle: 'Environmental Architecture',
    description: 'A building that responds to environmental conditions through adaptive systems.',
    year: '2019',
    location: 'Tel Aviv, Israel',
    type: 'Environmental Architecture',
    images: {
      main: '/works/MIST/Render Exterior.jpg',
      gallery: [
        '/works/MIST/0 Ground Floor.jpg',
        '/works/MIST/1st Floor.jpg',
        '/works/MIST/2nd Floor.jpg',
        '/works/MIST/Area Plan.jpg',
        '/works/MIST/Render Exterior.jpg',
        '/works/MIST/Render Main Hall.jpg',
        '/works/MIST/Render Roof.jpg',
        '/works/MIST/Render Treatment.jpg',
        '/works/MIST/Render Waterfall.jpg',
        '/works/MIST/Section.jpg',
        '/works/MIST/Timeline Diagram.jpg',
      ],
      thumbnails: [
        '/works/MIST/thumb/0 Ground Floor.jpg',
        '/works/MIST/thumb/1st Floor.jpg',
        '/works/MIST/thumb/2nd Floor.jpg',
        '/works/MIST/thumb/Area Plan.jpg',
        '/works/MIST/thumb/Render Exterior.jpg',
        '/works/MIST/thumb/Render Main Hall.jpg',
        '/works/MIST/thumb/Render Roof.jpg',
        '/works/MIST/thumb/Render Treatment.jpg',
        '/works/MIST/thumb/Render Waterfall.jpg',
        '/works/MIST/thumb/Section.jpg',
        '/works/MIST/thumb/Timeline Diagram.jpg',
      ],
    },
    videos: {
      main: '/works/MIST/Video/Video.webm',
      gallery: [
        '/works/MIST/Video/Video.webm',
        '/works/MIST/Video/Draft 1.webm',
        '/works/MIST/Video/Draft 2.webm',
      ],
    },
    text: {
      academic: 'MIST explores how architecture can actively respond to environmental conditions through adaptive building systems.',
      practical: 'The design incorporates responsive facades, natural ventilation systems, and water management strategies.',
      details: 'The building features a misting system that responds to temperature and humidity, creating microclimates throughout the space.',
    },
  },
  {
    id: 'umaguti',
    title: 'UMAGUTI',
    subtitle: 'Cultural Center',
    description: 'A cultural center celebrating local heritage and contemporary arts.',
    year: '2018',
    location: 'Tel Aviv, Israel',
    type: 'Cultural Architecture',
    images: {
      main: '/works/UMAGUTI/1.jpg',
      gallery: [
        '/works/UMAGUTI/1.jpg',
        '/works/UMAGUTI/2.jpg',
        '/works/UMAGUTI/3.jpg',
        '/works/UMAGUTI/4.jpg',
        '/works/UMAGUTI/5.jpg',
        '/works/UMAGUTI/6.jpg',
        '/works/UMAGUTI/7.jpg',
        '/works/UMAGUTI/8.jpg',
        '/works/UMAGUTI/9.jpg',
        '/works/UMAGUTI/10.jpg',
        '/works/UMAGUTI/11.jpg',
        '/works/UMAGUTI/12.jpg',
        '/works/UMAGUTI/13.jpg',
        '/works/UMAGUTI/14.jpg',
        '/works/UMAGUTI/15.jpg',
        '/works/UMAGUTI/16.jpg',
        '/works/UMAGUTI/17.jpg',
        '/works/UMAGUTI/18.jpg',
        '/works/UMAGUTI/19.jpg',
        '/works/UMAGUTI/20.jpg',
        '/works/UMAGUTI/21.jpg',
      ],
      thumbnails: [
        '/works/UMAGUTI/1.jpg',
        '/works/UMAGUTI/2.jpg',
        '/works/UMAGUTI/3.jpg',
        '/works/UMAGUTI/4.jpg',
        '/works/UMAGUTI/5.jpg',
        '/works/UMAGUTI/6.jpg',
        '/works/UMAGUTI/7.jpg',
        '/works/UMAGUTI/8.jpg',
        '/works/UMAGUTI/9.jpg',
        '/works/UMAGUTI/10.jpg',
        '/works/UMAGUTI/11.jpg',
        '/works/UMAGUTI/12.jpg',
        '/works/UMAGUTI/13.jpg',
        '/works/UMAGUTI/14.jpg',
        '/works/UMAGUTI/15.jpg',
        '/works/UMAGUTI/16.jpg',
        '/works/UMAGUTI/17.jpg',
        '/works/UMAGUTI/18.jpg',
        '/works/UMAGUTI/19.jpg',
        '/works/UMAGUTI/20.jpg',
        '/works/UMAGUTI/21.jpg',
      ],
    },
    videos: {
      main: '/works/UMAGUTI/Video/Video.webm',
      gallery: [
        '/works/UMAGUTI/Video/Video.webm',
        '/works/UMAGUTI/Video/Mesh Inflation.webm',
        '/works/UMAGUTI/Video/Apartment Optimization.webm',
      ],
    },
    text: {
      academic: 'UMAGUTI explores the relationship between traditional cultural practices and contemporary architectural expression.',
      practical: 'The design incorporates local materials and construction techniques while providing modern facilities for cultural activities.',
      details: 'The center includes exhibition spaces, performance areas, workshops, and community gathering spaces.',
    },
  },
  {
    id: 'clear-studio',
    title: 'CLEAR STUDIO',
    subtitle: 'Creative Workspace',
    description: 'A flexible workspace designed for creative professionals.',
    year: '2017',
    location: 'Tel Aviv, Israel',
    type: 'Commercial Architecture',
    images: {
      main: '/works/CLEAR STUDIO/Building Phases.jpg',
      gallery: [
        '/works/CLEAR STUDIO/Building Phases.jpg',
        '/works/CLEAR STUDIO/Interior View.jpg',
        '/works/CLEAR STUDIO/Night View 2.jpg',
        '/works/CLEAR STUDIO/Night View.jpg',
        '/works/CLEAR STUDIO/View From Ha-Heshmonaim.jpg',
        '/works/CLEAR STUDIO/View From Rothschild Blvd.jpg',
      ],
      thumbnails: [
        '/works/CLEAR STUDIO/thumb/Building Phases.jpg',
        '/works/CLEAR STUDIO/thumb/Interior View.jpg',
        '/works/CLEAR STUDIO/thumb/Night View 2.jpg',
        '/works/CLEAR STUDIO/thumb/Night View.jpg',
        '/works/CLEAR STUDIO/thumb/View From Ha-Heshmonaim.jpg',
        '/works/CLEAR STUDIO/thumb/View From Rothschild Blvd.jpg',
      ],
    },
    videos: {
      main: '/works/CLEAR_STUDIO/Video/Video.webm',
      gallery: [
        '/works/CLEAR_STUDIO/Video/Video.webm',
      ],
    },
    text: {
      academic: 'CLEAR STUDIO investigates how workspace design can support creative processes and collaboration.',
      practical: 'The design provides flexible spaces that can be reconfigured for different types of creative work.',
      details: 'The studio includes open work areas, private offices, meeting rooms, and exhibition spaces.',
    },
  },
  {
    id: 'hs-building',
    title: 'HS BUILDING',
    subtitle: 'Mixed-Use Development',
    description: 'A mixed-use building combining residential and commercial functions.',
    year: '2016',
    location: 'Tel Aviv, Israel',
    type: 'Mixed-Use Architecture',
    images: {
      main: '/works/HS BUILDING/RENDER_1 - Photo.jpg',
      gallery: [
        '/works/HS BUILDING/-1 FLOOR.jpg',
        '/works/HS BUILDING/0 GROUND FLOOR.jpg',
        '/works/HS BUILDING/1ST FLOOR.jpg',
        '/works/HS BUILDING/2ND FLOOR.jpg',
        '/works/HS BUILDING/3RD FLOOR.jpg',
        '/works/HS BUILDING/5TH FLOOR.jpg',
        '/works/HS BUILDING/ROOF FLOOR.jpg',
        '/works/HS BUILDING/Section.jpg',
        '/works/HS BUILDING/RENDER_1 - Photo.jpg',
        '/works/HS BUILDING/RENDER_2 - Photo.jpg',
        '/works/HS BUILDING/RENDER_3 - Photo.jpg',
        '/works/HS BUILDING/RENDER_4 - Photo.jpg',
        '/works/HS BUILDING/RENDER_5 - Photo.jpg',
      ],
      thumbnails: [
        '/works/HS BUILDING/thumb/-1 FLOOR.jpg',
        '/works/HS BUILDING/thumb/0 GROUND FLOOR.jpg',
        '/works/HS BUILDING/thumb/1ST FLOOR.jpg',
        '/works/HS BUILDING/thumb/2ND FLOOR.jpg',
        '/works/HS BUILDING/thumb/3RD FLOOR.jpg',
        '/works/HS BUILDING/thumb/5TH FLOOR.jpg',
        '/works/HS BUILDING/thumb/ROOF FLOOR.jpg',
        '/works/HS BUILDING/thumb/Section.jpg',
        '/works/HS BUILDING/thumb/RENDER_1 - Photo.jpg',
        '/works/HS BUILDING/thumb/RENDER_2 - Photo.jpg',
        '/works/HS BUILDING/thumb/RENDER_3 - Photo.jpg',
        '/works/HS BUILDING/thumb/RENDER_4 - Photo.jpg',
        '/works/HS BUILDING/thumb/RENDER_5 - Photo.jpg',
      ],
    },
    videos: {
      main: '/works/HS_BUILDING/Video/Video.webm',
      gallery: [
        '/works/HS_BUILDING/Video/Video.webm',
      ],
    },
    text: {
      academic: 'HS BUILDING explores the integration of residential and commercial functions in urban environments.',
      practical: 'The design creates a vertical neighborhood with shared amenities and flexible commercial spaces.',
      details: 'The building includes 50 residential units, ground-floor retail, and rooftop amenities.',
    },
  },
  {
    id: 'neot-shamir',
    title: 'NEOT SHAMIR',
    subtitle: 'Educational Campus',
    description: 'A new educational campus designed for collaborative learning.',
    year: '2015',
    location: 'Neot Shamir, Israel',
    type: 'Educational Architecture',
    images: {
      main: '/works/NEOT SHAMIR/school entrance.jpg',
      gallery: [
        '/works/NEOT SHAMIR/FENCE-BUILDING.jpg',
        '/works/NEOT SHAMIR/gan_int.jpg',
        '/works/NEOT SHAMIR/GAN-FRONT-VIEW3.jpg',
        '/works/NEOT SHAMIR/GAN-TOP VIEW.jpg',
        '/works/NEOT SHAMIR/Kindergarten_section_1-10-03.jpg',
        '/works/NEOT SHAMIR/school entrance - Copy_Thumb.jpg',
        '/works/NEOT SHAMIR/school entrance - Copy.jpg',
        '/works/NEOT SHAMIR/school entrance.jpg',
        '/works/NEOT SHAMIR/school-in-3.jpg',
        '/works/NEOT SHAMIR/school-park.jpg',
        '/works/NEOT SHAMIR/section_1-500-02.jpg',
      ],
      thumbnails: [
        '/works/NEOT SHAMIR/thumb/FENCE-BUILDING.jpg',
        '/works/NEOT SHAMIR/thumb/gan_int.jpg',
        '/works/NEOT SHAMIR/thumb/GAN-FRONT-VIEW3.jpg',
        '/works/NEOT SHAMIR/thumb/GAN-TOP VIEW.jpg',
        '/works/NEOT SHAMIR/thumb/Kindergarten_section_1-10-03.jpg',
        '/works/NEOT SHAMIR/thumb/school entrance - Copy_Thumb.jpg',
        '/works/NEOT SHAMIR/thumb/school entrance - Copy.jpg',
        '/works/NEOT SHAMIR/thumb/school entrance.jpg',
        '/works/NEOT SHAMIR/thumb/school-in-3.jpg',
        '/works/NEOT SHAMIR/thumb/school-park.jpg',
        '/works/NEOT SHAMIR/thumb/section_1-500-02.jpg',
      ],
    },
    videos: {
      main: '/works/NEOT_SHAMIR/Video/Video.webm',
      gallery: [
        '/works/NEOT_SHAMIR/Video/Video.webm',
      ],
    },
    text: {
      academic: 'NEOT SHAMIR explores how educational architecture can support different learning styles and age groups.',
      practical: 'The design creates distinct zones for different age groups while maintaining visual and spatial connections.',
      details: 'The campus includes kindergarten, elementary school, and community facilities with shared outdoor spaces.',
    },
  },
];

export const aboutText = {
  bio: 'Israeli born architect and creative coder. Holds a vast experience in design, fine arts, data analysis and programming. A firm believer in exploring and combining a wide array of practises, specifically within the intersection technology and art.',
  academic: 'Master of Architecture from the Technion - Israel Institute of Technology, with focus on computational design and digital fabrication.',
  practical: 'Over 10 years of experience in architectural design, from concept to construction, with expertise in parametric design and digital tools.',
  details: 'Currently working on projects that explore the intersection of architecture, technology, and art, with a focus on sustainable design and community engagement.',
};
